server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: CARD-SERVICE
          uri: http://localhost:7080
          predicates:
            - Path=/card/**
        - id: PAYMENT-SERVICE
          uri: http://localhost:8070
          predicates:
            - Path=/payment/**
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/oinshyk
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
